# -*- coding: utf-8 -*-
"""assistant_schema.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tFPCBcO-nfHN76GvrNfxJVeFLVoT06Ua
"""

from pydantic import BaseModel

class AssistantRequest(BaseModel):
    query: str